<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNfX6qkV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNfX6qkV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNfX6qkV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNfX6qkV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNfX6qkV\App_KernelDevDebugContainer([
    'container.build_hash' => 'NfX6qkV',
    'container.build_id' => '3d72062e',
    'container.build_time' => 1681128134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNfX6qkV');
