<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQBavbnd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQBavbnd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQBavbnd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQBavbnd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQBavbnd\App_KernelDevDebugContainer([
    'container.build_hash' => 'QBavbnd',
    'container.build_id' => '4fb7c50f',
    'container.build_time' => 1681120499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQBavbnd');
