<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBKoghUu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBKoghUu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBKoghUu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBKoghUu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBKoghUu\App_KernelDevDebugContainer([
    'container.build_hash' => 'BKoghUu',
    'container.build_id' => 'cbde700c',
    'container.build_time' => 1681037746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBKoghUu');
