<?php

namespace ContainerScJ03x3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOPHNqdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOPHNqd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOPHNqd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\StockController::stockAction' => ['privates', '.service_locator.FCwuPz2', 'get_ServiceLocator_FCwuPz2Service', true],
            'App\\Controller\\SupplyAddController::supplyAddAction' => ['privates', '.service_locator.IQL3rOg', 'get_ServiceLocator_IQL3rOgService', true],
            'App\\Controller\\SupplyController::supplyAction' => ['privates', '.service_locator.61kLFqt', 'get_ServiceLocator_61kLFqtService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\StockController:stockAction' => ['privates', '.service_locator.FCwuPz2', 'get_ServiceLocator_FCwuPz2Service', true],
            'App\\Controller\\SupplyAddController:supplyAddAction' => ['privates', '.service_locator.IQL3rOg', 'get_ServiceLocator_IQL3rOgService', true],
            'App\\Controller\\SupplyController:supplyAction' => ['privates', '.service_locator.61kLFqt', 'get_ServiceLocator_61kLFqtService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\StockController::stockAction' => '?',
            'App\\Controller\\SupplyAddController::supplyAddAction' => '?',
            'App\\Controller\\SupplyController::supplyAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\StockController:stockAction' => '?',
            'App\\Controller\\SupplyAddController:supplyAddAction' => '?',
            'App\\Controller\\SupplyController:supplyAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
