<?php

namespace ContainerNfX6qkV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_61kLFqtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.61kLFqt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.61kLFqt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'supplyRepository' => ['privates', 'App\\Repository\\SupplyRepository', 'getSupplyRepositoryService', true],
        ], [
            'supplyRepository' => 'App\\Repository\\SupplyRepository',
        ]);
    }
}
