<?php

namespace ContainerNfX6qkV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SupplyService' shared autowired service.
     *
     * @return \App\Service\SupplyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SupplyService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ProductService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/StockService.php';

        return $container->privates['App\\Service\\SupplyService'] = new \App\Service\SupplyService(($container->privates['App\\Repository\\SupplyRepository'] ?? $container->load('getSupplyRepositoryService')), new \App\Service\ProductService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'))), new \App\Service\StockService(($container->privates['App\\Repository\\StockRepository'] ?? $container->load('getStockRepositoryService'))));
    }
}
