<?php

namespace ContainerJykteON;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GKhxn19Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gKhxn19' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gKhxn19'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderService' => ['privates', 'App\\Service\\NewOrderService', 'getNewOrderServiceService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
        ], [
            'orderService' => 'App\\Service\\NewOrderService',
            'serializer' => '?',
        ]);
    }
}
