<?php

namespace ContainerQBavbnd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JeVsfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.je__Vsf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.je__Vsf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderService' => ['privates', 'App\\Service\\NewOrderService', 'getNewOrderServiceService', true],
        ], [
            'orderService' => 'App\\Service\\NewOrderService',
        ]);
    }
}
